### ISSUE TITLE
Reuse output

### ISSUE THREAD

**Issue by ghost** [lots0logs/gh-action-get-changed-files#18]
Regarding the output:
```
${HOME}/files.json
${HOME}/files_modified.json
${HOME}/files_added.json
${HOME}/files_deleted.json
${HOME}/files_renamed.json
```

How can we access these files in a subsequent **step**?

We are too blind to see.

We did now this but this cant be the solution:

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: mv ~/files.json .                                                                   <------
      - uses: REPO/actions/checkmarx-check@main
        if: ${{ always() }}
        with:
          touched-files-file: /github/workspace/files.json                     <------
```

But that is the biggest hack. How did you intent [these lines](https://github.com/lots0logs/gh-action-get-changed-files/blob/002a3dec1083f13f4e1853c5c1dc26526ac185bc/action.yml#L2)?
We also tried using `~` but it also seems hacky.

Appreciate it.

**Comment by lots0logs** [comment]
You should be able to access the files using the exact path shown in the readme. The `${HOME}` variable inside your container is set by GitHub Actions Runner when it runs the steps.

**Comment by mambax** [comment]
I am literally too stupid to use your readme then.
Can you apply my example?
How will I reference the file or the output in the next step? I stand on the tube here 🤣 Excuse me 😢 

```
      - uses: REPO/actions/checkmarx-check@main
        with:
          touched-files-file: How to reference file? Or output?
```

Update: Wait 1 sec. We do not use GH Actions Runner, we use self-hosted runners. Maybe that is the issue. Because our ${HOME} points to the **runners** home not the **container** home. 🔴

**Comment by lots0logs** [comment]
This action expects the runner to do what github's runners do regarding the mount points and environment variables: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#file-systems

That being said. You should be able to access the data as outputs of the action. I say should because while it is implemented I haven't tested it. We use the files to parse the output at my job. Here's an example of how to use the output of the action:

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: changed-files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: mv ~/files.json .                                                                   <------
      - uses: REPO/actions/checkmarx-check@main
        if: ${{ always() }}
        with:
          all-changed-files: ${{ steps.changed-files.outputs.all }}
```

You could even use the values directly in the config like this:
```
${{ fromJSON(steps.changed-files.all) }}  
```

Ref: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

**Comment by ghost** [comment]
I think something in our runner is off. I somehow think our `$HOME` is wrong. I printed with a Docker Action and on the runner the same script:

```
name: Log context

on:
  workflow_dispatch:

jobs:
  in-container:
    runs-on: [ aws ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./test

  runner:
    runs-on: [ aws ]
    steps:
      - run: |
          pwd
          echo $HOME
          ls -la $HOME
```

Action:
```
#!/bin/sh
pwd
echo $HOME
ls -la $HOME
```

The outputs respectively are

### Container
```
/github/workspace
/github/home
total 8
drwxr-xr-x    2 root     root          4096 Feb 19 07:56 .
drwxr-xr-x    6 root     root          4096 Feb 19 07:56 ..
```
### Runner (self-hosted)
```
/home/runners/actions-runner/_work/actions/actions
/home/runners
total 40
drwxr-xr-x 7 runners runners 4096 Feb 18 22:24 .
drwxr-xr-x 4 root    root    4096 Feb 18 22:07 ..
-rw-r--r-- 1 runners runners  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 runners runners 3771 Feb 25  2020 .bashrc
drwxrwxr-x 5 runners runners 4096 Feb 18 22:08 .config
drwx--x--x 3 runners runners 4096 Feb 18 22:07 .local
-rw-r--r-- 1 runners runners  999 Feb 18 22:07 .profile
drwxr-xr-x 6 runners runners 4096 Feb 18 22:23 actions-runner
drwxrwxr-x 2 runners runners 4096 Feb 18 22:07 bin
```

@lots0logs would you accept a PR where someone can specify an `output-directory`?

Update: I just ran exactly the same actions on public GH `ubuntu-latest` and the output is 1:1 the same 🤯
