### ISSUE TITLE
deleted files are not listed

### ISSUE THREAD

**Issue by supreethdevm** [lots0logs/gh-action-get-changed-files#5]
In the step name `list json file`, files_added.json and files_modified.json correctly contains the file names. However, files_deleted.json always is an empty array.

YML file I use:
```
on:
  push:
    branches:
    - master
    paths:
    - 'folder/**'
 
    
jobs:
  job1:
    runs-on: ubuntu-latest
  
    
    steps:
     - uses: actions/checkout@v1 
     - name: Get changed files
       uses: lots0logs/gh-action-get-changed-files@2.0.5
       with:
         token: ${{ secrets.personal_access_token }}
     - name: list json file
       run: |
        cat ${HOME}/files.json
        cat ${HOME}/files_modified.json
        cat ${HOME}/files_added.json
        cat ${HOME}/files_deleted.json
        ```
